CREATE TABLE IF NOT EXISTS saved_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL,
    title TEXT,
    employer TEXT,
    status TEXT DEFAULT 'saved',
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_applied TIMESTAMP WITH TIME ZONE
);
